name: Generate contribution snake

on:
  schedule:
    - cron: "17 */6 * * *"
  push:
    branches:
      - main
    paths-ignore:
      - "profile/streak.svg"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=#00B34A&color_dots=#ebedf0,#9be9a8,#40c463,#30a14e,#216e39
            dist/github-contribution-grid-snake-dark.svg?color_snake=#39D353&color_dots=#161B22,#0E4429,#006D32,#26A641,#39D353

      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
